-- Hapus semua data yang sudah ada sebelumnya
DELETE FROM `marketing_areas`;

-- Reset nomor ID / urutan agar kembali dari angka 1
ALTER TABLE `marketing_areas` AUTO_INCREMENT = 1;

-- Masukkan 81 data Kota/Kabupaten yang baru
INSERT INTO `marketing_areas` (`name`, `created_at`, `updated_at`) VALUES
('BOLAANG MONGONDOW', NOW(), NOW()),
('BOLAANG MONGONDOW SELATAN', NOW(), NOW()),
('BOLAANG MONGONDOW TIMUR', NOW(), NOW()),
('BOLAANG MONGONDOW UTARA', NOW(), NOW()),
('KEPULAUAN SANGIHE', NOW(), NOW()),
('KEPULAUAN SIAU TAGULANDANG BIARO', NOW(), NOW()),
('KEPULAUAN TALAUD', NOW(), NOW()),
('MINAHASA', NOW(), NOW()),
('MINAHASA SELATAN', NOW(), NOW()),
('MINAHASA TENGGARA', NOW(), NOW()),
('MINAHASA UTARA', NOW(), NOW()),
('BITUNG', NOW(), NOW()),
('KOTAMOBAGU', NOW(), NOW()),
('MANADO', NOW(), NOW()),
('TOMOHON', NOW(), NOW()),
('BOALEMO', NOW(), NOW()),
('BONE BOLANGO', NOW(), NOW()),
('GORONTALO', NOW(), NOW()),
('GORONTALO UTARA', NOW(), NOW()),
('POHUWATO', NOW(), NOW()),
('BANGGAI', NOW(), NOW()),
('BANGGAI KEPULAUAN', NOW(), NOW()),
('BANGGAI LAUT', NOW(), NOW()),
('BUOL', NOW(), NOW()),
('DONGGALA', NOW(), NOW()),
('MOROWALI', NOW(), NOW()),
('MOROWALI UTARA', NOW(), NOW()),
('PARIGI MOUTONG', NOW(), NOW()),
('POSO', NOW(), NOW()),
('SIGI', NOW(), NOW()),
('TOJO UNA-UNA', NOW(), NOW()),
('TOLITOLI', NOW(), NOW()),
('PALU', NOW(), NOW()),
('MAJENE', NOW(), NOW()),
('MAMASA', NOW(), NOW()),
('MAMUJU', NOW(), NOW()),
('MAMUJU TENGAH', NOW(), NOW()),
('PASANGKAYU', NOW(), NOW()),
('POLEWALI MANDAR', NOW(), NOW()),
('BANTAENG', NOW(), NOW()),
('BARRU', NOW(), NOW()),
('BONE', NOW(), NOW()),
('BULUKUMBA', NOW(), NOW()),
('ENREKANG', NOW(), NOW()),
('GOWA', NOW(), NOW()),
('JENEPONTO', NOW(), NOW()),
('KEPULAUAN SELAYAR', NOW(), NOW()),
('LUWU', NOW(), NOW()),
('LUWU TIMUR', NOW(), NOW()),
('LUWU UTARA', NOW(), NOW()),
('MAROS', NOW(), NOW()),
('PANGKAJENE DAN KEPULAUAN', NOW(), NOW()),
('PINRANG', NOW(), NOW()),
('SIDENRENG RAPPANG', NOW(), NOW()),
('SINJAI', NOW(), NOW()),
('SOPPENG', NOW(), NOW()),
('TAKALAR', NOW(), NOW()),
('TANA TORAJA', NOW(), NOW()),
('TORAJA UTARA', NOW(), NOW()),
('WAJO', NOW(), NOW()),
('MAKASSAR', NOW(), NOW()),
('PALOPO', NOW(), NOW()),
('PAREPARE', NOW(), NOW()),
('BOMBANA', NOW(), NOW()),
('BUTON', NOW(), NOW()),
('BUTON SELATAN', NOW(), NOW()),
('BUTON TENGAH', NOW(), NOW()),
('BUTON UTARA', NOW(), NOW()),
('KOLAKA', NOW(), NOW()),
('KOLAKA TIMUR', NOW(), NOW()),
('KOLAKA UTARA', NOW(), NOW()),
('KONAWE', NOW(), NOW()),
('KONAWE KEPULAUAN', NOW(), NOW()),
('KONAWE SELATAN', NOW(), NOW()),
('KONAWE UTARA', NOW(), NOW()),
('MUNA', NOW(), NOW()),
('MUNA BARAT', NOW(), NOW()),
('WAKATOBI', NOW(), NOW()),
('BAUBAU', NOW(), NOW()),
('KENDARI', NOW(), NOW());
